export enum ContentType {
  JSON = "application/json",
  FORM_URLENCODED = "application/x-www-form-urlencoded",
  FORM_DATA = "multipart/form-data",
  TEXT = "text/plain",
  HTML = "text/html",
  XML = "application/xml",
  JAVASCRIPT = "application/javascript",
  CSS = "text/css",
  CSV = "text/csv",
  PDF = "application/pdf",
  ZIP = "application/zip",
  OCTET_STREAM = "application/octet-stream",
  PNG = "image/png",
  JPEG = "image/jpeg",
  GIF = "image/gif",
  SVG = "image/svg+xml",
  WEBP = "image/webp",
  MP4 = "video/mp4",
  MPEG = "video/mpeg",
  MP3 = "audio/mpeg",
  OGG = "audio/ogg",
}
